import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> sadnessEntries = [
  EmotionKnowledgeEntry(id: 'sadness_01', scenario: '工作受挫，感到沮丧', emotionTags: ['沮丧', '失败'], strategies: ['回顾过往成就，肯定自我价值', '把大目标拆分为小步骤', '寻求同事或导师的支持'], contextTags: ['工作', '失败', '沮丧']),
  EmotionKnowledgeEntry(id: 'sadness_02', scenario: '考试成绩不理想', emotionTags: ['失落', '自责'], strategies: ['分析失分原因，制定改进计划', '允许自己难过一段时间', '和老师同学交流解题思路'], contextTags: ['考试', '成绩', '学习']),
  EmotionKnowledgeEntry(id: 'sadness_03', scenario: '被朋友误解或忽视', emotionTags: ['委屈', '伤心'], strategies: ['尝试冷静沟通表达感受', '换位思考对方可能的处境', '给自己一些独处时间调整'], contextTags: ['朋友', '误解', '社交']),
  EmotionKnowledgeEntry(id: 'sadness_04', scenario: '亲人离世或分离', emotionTags: ['悲痛', '思念'], strategies: ['允许自己充分悲伤', '通过写日记或倾诉表达情感', '保留纪念物，延续情感连接'], contextTags: ['亲人', '离世', '分离']),
  EmotionKnowledgeEntry(id: 'sadness_05', scenario: '失恋或感情破裂', emotionTags: ['心碎', '怀念'], strategies: ['给自己足够的恢复时间', '减少查看前任社交媒体', '投入新的兴趣爱好'], contextTags: ['恋爱', '分手', '感情']),
  EmotionKnowledgeEntry(id: 'sadness_06', scenario: '宠物生病或离世', emotionTags: ['心疼', '无助'], strategies: ['允许自己为宠物悲伤', '回忆与宠物的美好时光', '考虑领养新宠物纪念'], contextTags: ['宠物', '生病', '离世']),
  EmotionKnowledgeEntry(id: 'sadness_07', scenario: '感觉自己不够好', emotionTags: ['自卑', '挫败'], strategies: ['列出自己的优点和成就', '停止与他人比较', '练习自我肯定的积极语言'], contextTags: ['自卑', '比较', '自我价值']),
  EmotionKnowledgeEntry(id: 'sadness_08', scenario: '生活缺乏意义感', emotionTags: ['空虚', '迷茫'], strategies: ['尝试新的活动和体验', '帮助他人，获得价值感', '设定一个小的可实现目标'], contextTags: ['意义', '空虚', '迷茫']),
  EmotionKnowledgeEntry(id: 'sadness_09', scenario: '天气阴沉影响心情', emotionTags: ['低落', '倦怠'], strategies: ['打开窗帘增加光照', '做一些轻度运动提升情绪', '听欢快的音乐或看喜剧'], contextTags: ['天气', '阴天', '光照']),
  EmotionKnowledgeEntry(id: 'sadness_10', scenario: '长时间独处感到孤独', emotionTags: ['孤独', '寂寞'], strategies: ['主动联系朋友或家人', '参加社区活动', '养一株植物或宠物陪伴'], contextTags: ['独处', '孤独', '社交']),
  EmotionKnowledgeEntry(id: 'sadness_11', scenario: '工作被批评感到委屈', emotionTags: ['委屈', '不满'], strategies: ['区分批评内容和批评方式', '从批评中提取有价值的反馈', '向信任的人倾诉释放情绪'], contextTags: ['工作', '批评', '领导']),
  EmotionKnowledgeEntry(id: 'sadness_12', scenario: '看到新闻事件感到难过', emotionTags: ['悲伤', '无力'], strategies: ['限制负面新闻浏览时间', '关注力所能及的帮助行动', '和朋友讨论分享感受'], contextTags: ['新闻', '社会', '灾难']),
  EmotionKnowledgeEntry(id: 'sadness_13', scenario: '生活节奏太快喘不过气', emotionTags: ['疲惫', '压抑'], strategies: ['重新评估优先级和时间分配', '学会拒绝不必要的事务', '每天留出15分钟独处时间'], contextTags: ['忙碌', '压力', '时间']),
  EmotionKnowledgeEntry(id: 'sadness_14', scenario: '身体不适影响情绪', emotionTags: ['烦躁', '低落'], strategies: ['积极治疗身体问题', '告诉身边人自己不舒服', '做能让自己舒适的小事'], contextTags: ['身体', '健康', '生病']),
  EmotionKnowledgeEntry(id: 'sadness_15', scenario: '觉得自己不被理解', emotionTags: ['孤独', '委屈'], strategies: ['尝试更清晰地表达自己的想法', '寻找志同道合的群体', '接受不被所有人理解是正常的'], contextTags: ['理解', '表达', '孤独']),
  EmotionKnowledgeEntry(id: 'sadness_16', scenario: '对未来的不确定感到焦虑', emotionTags: ['焦虑', '迷茫'], strategies: ['专注当下能做的事', '写下担忧并评估现实可能性', '和有经验的人交流'], contextTags: ['未来', '不确定', '焦虑']),
  EmotionKnowledgeEntry(id: 'sadness_17', scenario: '失去了重要机会', emotionTags: ['遗憾', '失落'], strategies: ['接受已经发生的事实', '从中学习为下次机会准备', '相信还会有新的机会'], contextTags: ['机会', '错过', '遗憾']),
  EmotionKnowledgeEntry(id: 'sadness_18', scenario: '社交场合感到格格不入', emotionTags: ['不安', '疏离'], strategies: ['不必强求融入每个圈子', '寻找让自己舒适的社交方式', '一对一深度交流可能更适合你'], contextTags: ['社交', '场合', '融入']),
  EmotionKnowledgeEntry(id: 'sadness_19', scenario: '看到别人的幸福感到对比', emotionTags: ['羡慕', '失落'], strategies: ['提醒自己每人都有自己的节奏', '感恩自己拥有的东西', '把羡慕转化为行动的动力'], contextTags: ['比较', '幸福', '羡慕']),
  EmotionKnowledgeEntry(id: 'sadness_20', scenario: '晚上睡不着胡思乱想', emotionTags: ['失眠', '焦虑'], strategies: ['写下脑子里的想法清空大脑', '做渐进式肌肉放松', '听白噪音或冥想音频'], contextTags: ['失眠', '夜晚', '思考']),
  EmotionKnowledgeEntry(id: 'sadness_21', scenario: '觉得自己拖累了别人', emotionTags: ['愧疚', '自责'], strategies: ['认识到这种想法可能是过度解读', '主动表达感谢而非歉意', '在能力范围内做一些回馈'], contextTags: ['愧疚', '自责', '负担']),
  EmotionKnowledgeEntry(id: 'sadness_22', scenario: '反复回想过去的事', emotionTags: ['后悔', '执念'], strategies: ['提醒过去无法改变', '把注意力转到今天能做什么', '练习正念冥想活在当下'], contextTags: ['过去', '后悔', '执念']),
  EmotionKnowledgeEntry(id: 'sadness_23', scenario: '感觉自己在原地踏步', emotionTags: ['沮丧', '停滞'], strategies: ['对比半年前的自己看到进步', '学习一个新技能打破舒适区', '找mentor定期交流成长'], contextTags: ['成长', '停滞', '进步']),
  EmotionKnowledgeEntry(id: 'sadness_24', scenario: '被忽视或冷落', emotionTags: ['失落', '不被重视'], strategies: ['主动表达自己的需求', '加入重视你的社群', '先学会重视自己'], contextTags: ['忽视', '冷落', '重视']),
  EmotionKnowledgeEntry(id: 'sadness_25', scenario: '季节变化导致情绪低落', emotionTags: ['倦怠', '低落'], strategies: ['增加户外活动时间', '补充维生素D', '保持规律运动习惯'], contextTags: ['季节', '天气', '光照']),
  EmotionKnowledgeEntry(id: 'sadness_26', scenario: '工作和生活失衡', emotionTags: ['疲惫', '不满'], strategies: ['设定明确的工作和生活界限', '学会说不，保护个人时间', '定期评估自己的状态'], contextTags: ['平衡', '工作', '生活']),
  EmotionKnowledgeEntry(id: 'sadness_27', scenario: '感觉没有人在乎自己', emotionTags: ['被遗忘', '孤独'], strategies: ['主动联系老朋友', '参与志愿活动建立连接', '先学会关爱自己'], contextTags: ['在乎', '孤独', '社交']),
  EmotionKnowledgeEntry(id: 'sadness_28', scenario: '自己的努力没有得到认可', emotionTags: ['失落', '不公'], strategies: ['认可自己的努力本身就有价值', '主动展示自己的成果', '寻找真正认可你的环境'], contextTags: ['认可', '努力', '价值']),
  EmotionKnowledgeEntry(id: 'sadness_29', scenario: '和家人关系紧张', emotionTags: ['心痛', '无奈'], strategies: ['选择合适的时机沟通', '先倾听对方的想法和感受', '不强求立刻解决所有问题'], contextTags: ['家庭', '关系', '紧张']),
  EmotionKnowledgeEntry(id: 'sadness_30', scenario: '对生活失去热情', emotionTags: ['麻木', '倦怠'], strategies: ['尝试做一些以前喜欢但很久没做的事', '给自己放一个小假', '和充满活力的人在一起'], contextTags: ['热情', '倦怠', '麻木']),
  EmotionKnowledgeEntry(id: 'sadness_31', scenario: '感到被世界抛弃', emotionTags: ['绝望', '孤独'], strategies: ['记住低谷终会过去', '联系信任的人或热线寻求帮助', '专注于身边的一个小美好'], contextTags: ['绝望', '孤独', '被抛弃']),
  EmotionKnowledgeEntry(id: 'sadness_32', scenario: '对自己的选择感到后悔', emotionTags: ['后悔', '迷茫'], strategies: ['接受已经做出的选择', '思考从中学到了什么', '现在开始做出新的改变'], contextTags: ['选择', '后悔', '迷茫']),
  EmotionKnowledgeEntry(id: 'sadness_33', scenario: '收到坏消息', emotionTags: ['震惊', '难过'], strategies: ['给自己时间消化', '寻求身边人的支持', '专注处理眼前能做的事'], contextTags: ['消息', '意外', '震惊']),
  EmotionKnowledgeEntry(id: 'sadness_34', scenario: '觉得自己辜负了期望', emotionTags: ['愧疚', '压力'], strategies: ['区分合理期望和不合理期望', '和期望者坦诚沟通', '把压力转化为有计划的行动'], contextTags: ['期望', '辜负', '压力']),
  EmotionKnowledgeEntry(id: 'sadness_35', scenario: '深夜感到莫名的悲伤', emotionTags: ['悲伤', '脆弱'], strategies: ['允许自己感受悲伤', '做几次深呼吸平复', '提醒自己明天会好起来'], contextTags: ['深夜', '悲伤', '脆弱']),
];
