import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> lonelinessEntries = [
  EmotionKnowledgeEntry(id: 'loneliness_01', scenario: '一个人吃饭感到孤独', emotionTags: ['孤独', '寂寞'], strategies: ['享受独处的时光', '边吃边听喜欢的节目', '偶尔约朋友一起吃饭'], contextTags: ['吃饭', '独处', '一个人']),
  EmotionKnowledgeEntry(id: 'loneliness_02', scenario: '搬到新城市没有朋友', emotionTags: ['孤独', '陌生'], strategies: ['参加兴趣社群认识新朋友', '和同事或邻居建立关系', '保持和老家朋友的联系'], contextTags: ['搬家', '新城市', '社交']),
  EmotionKnowledgeEntry(id: 'loneliness_03', scenario: '深夜想找人聊天找不到人', emotionTags: ['孤独', '渴望'], strategies: ['在日记中写下感受', '加入24小时心理支持群', '给自己一个拥抱'], contextTags: ['深夜', '聊天', '陪伴']),
  EmotionKnowledgeEntry(id: 'loneliness_04', scenario: '热闹的人群中依然感到孤独', emotionTags: ['疏离', '空虚'], strategies: ['尝试和一个人深入交流', '接受孤独感有时是正常的', '找到让你有归属感的群体'], contextTags: ['人群', '疏离', '热闹']),
  EmotionKnowledgeEntry(id: 'loneliness_05', scenario: '分手后感到世界空荡荡', emotionTags: ['孤独', '失落'], strategies: ['给自己足够的恢复时间', '重新发现独处的乐趣', '和朋友家人多待在一起'], contextTags: ['分手', '失落', '空荡']),
  EmotionKnowledgeEntry(id: 'loneliness_06', scenario: '社交网络上看到朋友聚会没叫你', emotionTags: ['被遗忘', '失落'], strategies: ['主动联系朋友表达想见面', '组织自己的聚会', '朋友圈不一定是全部'], contextTags: ['社交', '聚会', '遗忘']),
  EmotionKnowledgeEntry(id: 'loneliness_07', scenario: '家人在身边但不理解自己', emotionTags: ['隔阂', '孤独'], strategies: ['尝试用不同的方式表达', '寻找能理解你的人', '接受家人有他们的局限'], contextTags: ['家人', '理解', '隔阂']),
  EmotionKnowledgeEntry(id: 'loneliness_08', scenario: '生病时没有人照顾', emotionTags: ['孤独', '脆弱'], strategies: ['提前和朋友建立互助关系', '学会照顾自己', '生病时给自己最好的关怀'], contextTags: ['生病', '照顾', '脆弱']),
  EmotionKnowledgeEntry(id: 'loneliness_09', scenario: '工作之余没有社交活动', emotionTags: ['单调', '孤独'], strategies: ['发展一个兴趣爱好', '加入运动或读书俱乐部', '定期和朋友约见面'], contextTags: ['工作', '社交', '单调']),
  EmotionKnowledgeEntry(id: 'loneliness_10', scenario: '在国外感到文化隔阂', emotionTags: ['疏离', '孤独'], strategies: ['寻找华人或同乡社群', '学习当地文化融入', '保持与家人视频联系'], contextTags: ['国外', '文化', '隔阂']),
  EmotionKnowledgeEntry(id: 'loneliness_11', scenario: '看到别人成双成对感到羡慕', emotionTags: ['羡慕', '孤独'], strategies: ['单身也是完整的生活', '投资自己的成长和幸福', '好的感情会来的'], contextTags: ['恋爱', '单身', '羡慕']),
  EmotionKnowledgeEntry(id: 'loneliness_12', scenario: '退休后生活空虚', emotionTags: ['空虚', '失落'], strategies: ['发展新的兴趣爱好', '做志愿者帮助他人', '加入老年活动中心'], contextTags: ['退休', '空虚', '生活']),
  EmotionKnowledgeEntry(id: 'loneliness_13', scenario: '周末一个人不知道做什么', emotionTags: ['无聊', '孤独'], strategies: ['尝试新的体验和活动', '享受安静的阅读时光', '去公园散步接触自然'], contextTags: ['周末', '无聊', '独处']),
  EmotionKnowledgeEntry(id: 'loneliness_14', scenario: '在公司没有归属感', emotionTags: ['疏离', '不融入'], strategies: ['主动参与团队活动', '找到一两个关系好的同事', '专注于自己的专业成长'], contextTags: ['公司', '归属', '融入']),
  EmotionKnowledgeEntry(id: 'loneliness_15', scenario: '觉得没有人真正懂自己', emotionTags: ['被误解', '孤独'], strategies: ['先尝试理解自己', '找到兴趣相似的人', '深度关系需要时间培养'], contextTags: ['理解', '懂', '共鸣']),
  EmotionKnowledgeEntry(id: 'loneliness_16', scenario: '节日一个人过', emotionTags: ['冷清', '孤独'], strategies: ['给自己准备一份礼物', '视频连线远方的朋友', '参与社区的节日活动'], contextTags: ['节日', '冷清', '一个人']),
  EmotionKnowledgeEntry(id: 'loneliness_17', scenario: '害怕打扰别人不敢联系', emotionTags: ['退缩', '犹豫'], strategies: ['真正的朋友不会觉得被打扰', '简单的问候也温暖人心', '主动联系是友谊的维护'], contextTags: ['联系', '打扰', '犹豫']),
  EmotionKnowledgeEntry(id: 'loneliness_18', scenario: '感觉自己是多余的', emotionTags: ['无价值', '孤独'], strategies: ['你对世界的存在本身就有价值', '去帮助一个需要帮助的人', '找到让你觉得被需要的事'], contextTags: ['多余', '价值', '存在']),
  EmotionKnowledgeEntry(id: 'loneliness_19', scenario: '孩子长大离家感到空巢', emotionTags: ['失落', '空虚'], strategies: ['重新发现和伴侣的关系', '发展自己的兴趣爱好', '做自己年轻时想做但没时间做的事'], contextTags: ['孩子', '离家', '空巢']),
  EmotionKnowledgeEntry(id: 'loneliness_20', scenario: '感觉没有人关心自己', emotionTags: ['被忽视', '孤独'], strategies: ['先学会关心和爱护自己', '主动参与社区活动', '可能有人在默默关心你'], contextTags: ['关心', '忽视', '在乎']),
  EmotionKnowledgeEntry(id: 'loneliness_21', scenario: '晚上独自走在路上', emotionTags: ['孤单', '脆弱'], strategies: ['保持安全意识', '给自己放喜欢的音乐', '享受夜色的宁静'], contextTags: ['夜晚', '走路', '孤单']),
  EmotionKnowledgeEntry(id: 'loneliness_22', scenario: '和老朋友渐渐疏远', emotionTags: ['怀念', '失落'], strategies: ['定期主动联系维护友谊', '接受关系的变化是正常的', '珍惜当下的友谊'], contextTags: ['老朋友', '疏远', '怀念']),
  EmotionKnowledgeEntry(id: 'loneliness_23', scenario: '患了心理疾病感到孤立', emotionTags: ['孤立', '羞耻'], strategies: ['心理疾病不是你的错', '寻找互助小组获得支持', '专业的帮助很重要'], contextTags: ['心理', '疾病', '孤立']),
  EmotionKnowledgeEntry(id: 'loneliness_24', scenario: '在人群中找不到可以说话的人', emotionTags: ['疏离', '渴望'], strategies: ['主动微笑和打招呼', '从简单的闲聊开始', '不是每次交流都需要很深入'], contextTags: ['人群', '说话', '社交']),
  EmotionKnowledgeEntry(id: 'loneliness_25', scenario: '感觉身边都是假朋友', emotionTags: ['失望', '孤独'], strategies: ['区分社交关系和真正的朋友', '减少无效社交', '培养2-3个真正的友谊'], contextTags: ['假朋友', '社交', '失望']),
  EmotionKnowledgeEntry(id: 'loneliness_26', scenario: '一个人过生日', emotionTags: ['冷清', '失落'], strategies: ['给自己一个特别的生日礼物', '约几个好朋友一起庆祝', '生日也可以是感恩自己的日子'], contextTags: ['生日', '冷清', '独自']),
  EmotionKnowledgeEntry(id: 'loneliness_27', scenario: '搬到新小区不认识邻居', emotionTags: ['陌生', '疏离'], strategies: ['在电梯或走廊主动打招呼', '参与社区活动', '慢慢建立邻里关系'], contextTags: ['小区', '邻居', '陌生']),
  EmotionKnowledgeEntry(id: 'loneliness_28', scenario: '感觉自己在这个世界是孤岛', emotionTags: ['绝望', '孤独'], strategies: ['每个人都是一座孤岛但有桥相连', '主动走出去建立连接', '专业的心理咨询可以帮助'], contextTags: ['孤岛', '绝望', '连接']),
  EmotionKnowledgeEntry(id: 'loneliness_29', scenario: '养的植物死了没人一起难过', emotionTags: ['孤独', '小伤感'], strategies: ['允许自己为小事难过', '再养一株新的开始', '这种难过说明你有感受力'], contextTags: ['植物', '死亡', '孤独']),
  EmotionKnowledgeEntry(id: 'loneliness_30', scenario: '周末同事都出去玩了没人叫你', emotionTags: ['被遗忘', '失落'], strategies: ['下次主动提出一起参加', '自己安排一个愉快的周末', '不是所有聚会你都需要参加'], contextTags: ['周末', '同事', '遗忘']),
  EmotionKnowledgeEntry(id: 'loneliness_31', scenario: '深夜独自看电影感到寂寞', emotionTags: ['寂寞', '渴望'], strategies: ['享受沉浸式的观影体验', '看完和朋友分享感受', '加入影迷社群讨论'], contextTags: ['电影', '深夜', '寂寞']),
  EmotionKnowledgeEntry(id: 'loneliness_32', scenario: '在网络上潜水不参与讨论', emotionTags: ['观望', '孤独'], strategies: ['试着发一条友善的评论', '找到感兴趣的话题参与', '每个人都是从旁观者开始的'], contextTags: ['网络', '潜水', '参与']),
  EmotionKnowledgeEntry(id: 'loneliness_33', scenario: '感觉身边没人能帮自己', emotionTags: ['无助', '孤独'], strategies: ['列出可以求助的人和渠道', '你不必一个人承担所有', '社区和专业机构也能提供帮助'], contextTags: ['求助', '无助', '支持']),
  EmotionKnowledgeEntry(id: 'loneliness_34', scenario: '毕业和同学各奔东西', emotionTags: ['怀念', '孤独'], strategies: ['建立同学群保持联系', '珍惜在校的每一天', '新的城市会有新的朋友'], contextTags: ['毕业', '离别', '同学']),
  EmotionKnowledgeEntry(id: 'loneliness_35', scenario: '在群体中发言没人回应', emotionTags: ['尴尬', '失落'], strategies: ['不是你不好，可能是时机不对', '换一种方式表达', '找到愿意倾听的人'], contextTags: ['发言', '回应', '尴尬']),
];
