import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> happinessEntries = [
  EmotionKnowledgeEntry(id: 'happiness_01', scenario: '完成了一个目标感到成就感', emotionTags: ['成就感', '满足'], strategies: ['记录这份成就感', '和别人分享喜悦', '给自己一个小奖励'], contextTags: ['目标', '完成', '成就']),
  EmotionKnowledgeEntry(id: 'happiness_02', scenario: '和朋友开心地聚会', emotionTags: ['快乐', '温暖'], strategies: ['珍惜当下的快乐时光', '记录美好的瞬间', '表达对朋友的感谢'], contextTags: ['朋友', '聚会', '快乐']),
  EmotionKnowledgeEntry(id: 'happiness_03', scenario: '学会了一个新技能', emotionTags: ['兴奋', '自信'], strategies: ['给自己鼓掌', '继续深入学习', '教给别人巩固所学'], contextTags: ['学习', '技能', '成长']),
  EmotionKnowledgeEntry(id: 'happiness_04', scenario: '帮助了别人感到很开心', emotionTags: ['温暖', '价值'], strategies: ['感受这份助人的喜悦', '继续保持善意', '帮助别人也是帮助自己'], contextTags: ['帮助', '开心', '价值']),
  EmotionKnowledgeEntry(id: 'happiness_05', scenario: '天气好心情也好', emotionTags: ['愉悦', '轻松'], strategies: ['出门走走享受好天气', '和阳光来个亲密接触', '把好心情传递给身边人'], contextTags: ['天气', '阳光', '心情']),
  EmotionKnowledgeEntry(id: 'happiness_06', scenario: '收到意想不到的礼物', emotionTags: ['惊喜', '感动'], strategies: ['表达真诚的感谢', '这份心意比礼物更重要', '也给对方准备一个惊喜'], contextTags: ['礼物', '惊喜', '感动']),
  EmotionKnowledgeEntry(id: 'happiness_07', scenario: '和喜欢的人在一起', emotionTags: ['幸福', '安心'], strategies: ['珍惜在一起的时光', '表达你对对方的在乎', '一起创造更多美好回忆'], contextTags: ['喜欢', '在一起', '幸福']),
  EmotionKnowledgeEntry(id: 'happiness_08', scenario: '运动后身心舒畅', emotionTags: ['畅快', '满足'], strategies: ['坚持运动习惯', '享受运动带来的内啡肽', '尝试不同的运动方式'], contextTags: ['运动', '舒畅', '健康']),
  EmotionKnowledgeEntry(id: 'happiness_09', scenario: '看了一部好电影', emotionTags: ['满足', '感动'], strategies: ['写下感受记录这一刻', '和朋友分享观后感', '寻找同类型的好作品'], contextTags: ['电影', '满足', '感动']),
  EmotionKnowledgeEntry(id: 'happiness_10', scenario: '和孩子一起玩耍', emotionTags: ['温馨', '快乐'], strategies: ['享受纯真的快乐时光', '放下手机全身心陪伴', '记录这些珍贵瞬间'], contextTags: ['孩子', '玩耍', '温馨']),
  EmotionKnowledgeEntry(id: 'happiness_11', scenario: '被夸奖感到开心', emotionTags: ['自豪', '高兴'], strategies: ['坦然接受赞美', '记住这份肯定', '继续努力做得更好'], contextTags: ['夸奖', '开心', '肯定']),
  EmotionKnowledgeEntry(id: 'happiness_12', scenario: '和宠物亲密互动', emotionTags: ['治愈', '温暖'], strategies: ['享受无条件的爱', '照顾好毛孩子', '宠物是很好的情感支持'], contextTags: ['宠物', '治愈', '互动']),
  EmotionKnowledgeEntry(id: 'happiness_13', scenario: '旅行看到美丽的风景', emotionTags: ['震撼', '自由'], strategies: ['用相机或画笔记录', '感受大自然的壮阔', '旅行让人心胸开阔'], contextTags: ['旅行', '风景', '自由']),
  EmotionKnowledgeEntry(id: 'happiness_14', scenario: '自己做的饭被夸好吃', emotionTags: ['满足', '自豪'], strategies: ['享受烹饪的乐趣', '尝试更多新菜式', '和更多人分享你的手艺'], contextTags: ['做饭', '好吃', '满足']),
  EmotionKnowledgeEntry(id: 'happiness_15', scenario: '读书获得新知感到充实', emotionTags: ['充实', '好奇'], strategies: ['保持阅读的习惯', '和别人讨论书中的内容', '写下读书笔记加深理解'], contextTags: ['读书', '知识', '充实']),
  EmotionKnowledgeEntry(id: 'happiness_16', scenario: '清晨被鸟鸣唤醒', emotionTags: ['宁静', '愉悦'], strategies: ['早起感受晨光', '深呼吸感受新的一天', '给自己准备一份早餐'], contextTags: ['清晨', '鸟鸣', '宁静']),
  EmotionKnowledgeEntry(id: 'happiness_17', scenario: '克服了一个恐惧', emotionTags: ['勇气', '骄傲'], strategies: ['记录这次突破', '和别人分享你的勇气', '每次突破都让你更强'], contextTags: ['恐惧', '克服', '勇气']),
  EmotionKnowledgeEntry(id: 'happiness_18', scenario: '意外收到好评或认可', emotionTags: ['惊喜', '欣慰'], strategies: ['把好评截图保存', '这份认可是你努力的结果', '继续保持好的表现'], contextTags: ['好评', '认可', '惊喜']),
  EmotionKnowledgeEntry(id: 'happiness_19', scenario: '和老朋友重逢', emotionTags: ['怀念', '开心'], strategies: ['珍惜重逢的时光', '回忆共同的美好时光', '保持联系不让友谊褪色'], contextTags: ['朋友', '重逢', '怀念']),
  EmotionKnowledgeEntry(id: 'happiness_20', scenario: '周末睡到自然醒', emotionTags: ['放松', '满足'], strategies: ['好好享受这份慵懒', '给自己做一顿美味早餐', '不设闹钟的早晨最幸福'], contextTags: ['周末', '自然醒', '放松']),
  EmotionKnowledgeEntry(id: 'happiness_21', scenario: '收到工资或奖金', emotionTags: ['满足', '安全'], strategies: ['合理规划使用', '奖励自己一个小愿望', '存一部分为未来做准备'], contextTags: ['工资', '奖金', '满足']),
  EmotionKnowledgeEntry(id: 'happiness_22', scenario: '听到一首歌很有共鸣', emotionTags: ['感动', '共鸣'], strategies: ['反复听感受音乐的力量', '分享给懂你的人', '把感受写下来'], contextTags: ['音乐', '共鸣', '感动']),
  EmotionKnowledgeEntry(id: 'happiness_23', scenario: '种的花开了', emotionTags: ['喜悦', '成就'], strategies: ['享受生命成长的美好', '拍照记录这一刻', '继续照料它绽放更久'], contextTags: ['花', '种植', '喜悦']),
  EmotionKnowledgeEntry(id: 'happiness_24', scenario: '家人健康平安', emotionTags: ['安心', '感恩'], strategies: ['珍惜平凡的幸福', '经常表达对家人的爱', '健康是最大的财富'], contextTags: ['家人', '健康', '平安']),
  EmotionKnowledgeEntry(id: 'happiness_25', scenario: '和同事合作很愉快', emotionTags: ['愉快', '满足'], strategies: ['珍惜好的工作氛围', '表达对同事的认可', '好的合作是双向的'], contextTags: ['同事', '合作', '愉快']),
  EmotionKnowledgeEntry(id: 'happiness_26', scenario: '在图书馆找到想看的书', emotionTags: ['幸运', '满足'], strategies: ['享受阅读的时光', '借阅其他感兴趣的书', '图书馆是宝藏'], contextTags: ['图书馆', '书', '幸运']),
  EmotionKnowledgeEntry(id: 'happiness_27', scenario: '和朋友一起做饭', emotionTags: ['温暖', '快乐'], strategies: ['享受一起劳动的乐趣', '分享各自拿手的菜', '过程比结果更重要'], contextTags: ['做饭', '朋友', '温暖']),
  EmotionKnowledgeEntry(id: 'happiness_28', scenario: '坐公交刚好赶上了', emotionTags: ['幸运', '高兴'], strategies: ['享受这份小确幸', '好的开始是成功的一半', '今天运气不错'], contextTags: ['公交', '幸运', '赶上了']),
  EmotionKnowledgeEntry(id: 'happiness_29', scenario: '完成了一次自我突破', emotionTags: ['自豪', '成长'], strategies: ['记录这次突破的经历', '你比你想象的更强大', '每次突破都是成长'], contextTags: ['突破', '成长', '自豪']),
  EmotionKnowledgeEntry(id: 'happiness_30', scenario: '孩子第一次叫爸爸妈妈', emotionTags: ['感动', '幸福'], strategies: ['这是为人父母最幸福的时刻', '记录这个里程碑', '陪伴孩子成长的每一天都很珍贵'], contextTags: ['孩子', '第一次', '感动']),
  EmotionKnowledgeEntry(id: 'happiness_31', scenario: '在异乡吃到家乡的味道', emotionTags: ['怀念', '满足'], strategies: ['味道是最强的记忆触发器', '和身边人分享家乡美食', '有空回家看看'], contextTags: ['家乡', '味道', '怀念']),
  EmotionKnowledgeEntry(id: 'happiness_32', scenario: '终于鼓起勇气做了一件事', emotionTags: ['勇气', '释放'], strategies: ['为自己的勇气鼓掌', '做了就比不做好', '以后会越来越勇敢'], contextTags: ['勇气', '做', '突破']),
  EmotionKnowledgeEntry(id: 'happiness_33', scenario: '和喜欢的人一起看日落', emotionTags: ['浪漫', '幸福'], strategies: ['珍惜这个美好的瞬间', '用照片或文字记录', '浪漫不需要很贵'], contextTags: ['日落', '浪漫', '一起']),
  EmotionKnowledgeEntry(id: 'happiness_34', scenario: '被治愈的瞬间', emotionTags: ['治愈', '温暖'], strategies: ['记住这个瞬间', '把它当作能量储备', '你也可能在治愈别人'], contextTags: ['治愈', '温暖', '瞬间']),
  EmotionKnowledgeEntry(id: 'happiness_35', scenario: '感到生活充满希望', emotionTags: ['希望', '乐观'], strategies: ['保持这份希望', '为自己设定新的目标', '你值得拥有美好的未来'], contextTags: ['希望', '未来', '乐观']),
];
