import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> anxietyEntries = [
  EmotionKnowledgeEntry(id: 'anxiety_01', scenario: '考试前紧张不安', emotionTags: ['紧张', '担心'], strategies: ['提前准备减少不确定性', '练习深呼吸放松', '合理安排复习时间表'], contextTags: ['考试', '紧张', '学习']),
  EmotionKnowledgeEntry(id: 'anxiety_02', scenario: '等待重要结果', emotionTags: ['焦虑', '不安'], strategies: ['做其他事情分散注意力', '接受结果不完全在掌控中', '练习冥想平复心情'], contextTags: ['等待', '结果', '不确定']),
  EmotionKnowledgeEntry(id: 'anxiety_03', scenario: '担心未来不知道该怎么办', emotionTags: ['迷茫', '焦虑'], strategies: ['专注当下能做的事', '和有经验的人交流', '写下来具体担忧是什么'], contextTags: ['未来', '迷茫', '焦虑']),
  EmotionKnowledgeEntry(id: 'anxiety_04', scenario: '社交场合怕说错话', emotionTags: ['紧张', '害怕'], strategies: ['提前准备一些话题', '关注对方而非自己', '犯错也没关系大多数人不会记得'], contextTags: ['社交', '说话', '紧张']),
  EmotionKnowledgeEntry(id: 'anxiety_05', scenario: '身体不适时担心得了大病', emotionTags: ['恐惧', '焦虑'], strategies: ['先去正规医院检查', '减少搜索症状信息', '信任医生的专业判断'], contextTags: ['健康', '生病', '恐惧']),
  EmotionKnowledgeEntry(id: 'anxiety_06', scenario: '被催促做决定感到压力', emotionTags: ['焦虑', '急迫'], strategies: ['给自己设定一个合理的时间', '列出选择的利弊', '必要时说需要更多时间'], contextTags: ['决定', '催促', '压力']),
  EmotionKnowledgeEntry(id: 'anxiety_07', scenario: '担心失去工作', emotionTags: ['不安全', '恐惧'], strategies: ['提升自己的核心竞争力', '建立职业储备计划', '关注行业动态做好准备'], contextTags: ['工作', '失业', '安全']),
  EmotionKnowledgeEntry(id: 'anxiety_08', scenario: '和别人比较感到不足', emotionTags: ['自卑', '焦虑'], strategies: ['只和昨天的自己比较', '专注自己的成长轨迹', '每个人的时间线不同'], contextTags: ['比较', '不足', '自卑']),
  EmotionKnowledgeEntry(id: 'anxiety_09', scenario: '人多的地方感到窒息', emotionTags: ['恐慌', '窒息'], strategies: ['提前规划好离场路线', '练习4-7-8呼吸法', '带一个信任的人同行'], contextTags: ['人多', '恐慌', '拥挤']),
  EmotionKnowledgeEntry(id: 'anxiety_10', scenario: '凌晨三四点醒来睡不着', emotionTags: ['失眠', '焦虑'], strategies: ['不强迫自己入睡，起来做放松的事', '练习渐进式肌肉放松', '调整睡眠环境温度和光线'], contextTags: ['失眠', '凌晨', '睡眠']),
  EmotionKnowledgeEntry(id: 'anxiety_11', scenario: '觉得时间不够用', emotionTags: ['紧迫', '烦躁'], strategies: ['用番茄工作法提高效率', '区分紧急和重要事务', '接受不可能做完所有事'], contextTags: ['时间', '紧迫', '效率']),
  EmotionKnowledgeEntry(id: 'anxiety_12', scenario: '发消息后对方很久没回', emotionTags: ['胡思乱想', '不安'], strategies: ['对方可能只是在忙，不要过度解读', '做点别的事转移注意力', '直接打个电话确认'], contextTags: ['消息', '回复', '等待']),
  EmotionKnowledgeEntry(id: 'anxiety_13', scenario: '花钱后感到后悔和自责', emotionTags: ['后悔', '内疚'], strategies: ['区分需要和想要', '制定合理的消费预算', '允许自己偶尔享受生活'], contextTags: ['消费', '后悔', '自责']),
  EmotionKnowledgeEntry(id: 'anxiety_14', scenario: '坐飞机或坐车时恐惧', emotionTags: ['恐惧', '紧张'], strategies: ['了解交通工具的安全数据', '听音乐或看电影分散注意力', '和旁边的人聊天缓解紧张'], contextTags: ['出行', '交通', '恐惧']),
  EmotionKnowledgeEntry(id: 'anxiety_15', scenario: '担心自己能力不足', emotionTags: ['不自信', '焦虑'], strategies: ['记录自己的成功经历', '把大任务分解成小步骤', '每个人都有不擅长的领域'], contextTags: ['能力', '不自信', '担心']),
  EmotionKnowledgeEntry(id: 'anxiety_16', scenario: '计划突然被打乱', emotionTags: ['烦躁', '不安'], strategies: ['练习接受不可控的变化', '保留一些弹性时间', '关注新的可能性而非损失'], contextTags: ['计划', '变化', '意外']),
  EmotionKnowledgeEntry(id: 'anxiety_17', scenario: '独自在家感到害怕', emotionTags: ['恐惧', '不安'], strategies: ['检查门窗确保安全', '听熟悉的音乐或广播', '和朋友通电话聊天'], contextTags: ['独处', '害怕', '安全']),
  EmotionKnowledgeEntry(id: 'anxiety_18', scenario: '担心被别人评判', emotionTags: ['紧张', '不自在'], strategies: ['大多数人其实没有那么关注你', '专注于做对的事而非看起来对', '和让你舒服的人在一起'], contextTags: ['评判', '社交', '关注']),
  EmotionKnowledgeEntry(id: 'anxiety_19', scenario: '心脏跳得快感到恐慌', emotionTags: ['恐慌', '恐惧'], strategies: ['先坐下休息，做缓慢深呼吸', '这是焦虑的正常身体反应', '如果持续不缓解请就医'], contextTags: ['心跳', '恐慌', '身体']),
  EmotionKnowledgeEntry(id: 'anxiety_20', scenario: '要见新的人感到紧张', emotionTags: ['紧张', '期待'], strategies: ['准备几个开放式问题', '把注意力放在了解对方上', '提醒自己对方可能也紧张'], contextTags: ['见面', '新人', '紧张']),
  EmotionKnowledgeEntry(id: 'anxiety_21', scenario: '开车时担心出事故', emotionTags: ['恐惧', '紧张'], strategies: ['安全驾驶是最基本的预防', '避免疲劳驾驶', '定期检查车辆状况'], contextTags: ['驾驶', '安全', '恐惧']),
  EmotionKnowledgeEntry(id: 'anxiety_22', scenario: '签合同前犹豫不决', emotionTags: ['犹豫', '不安'], strategies: ['仔细阅读每一条款', '不懂的部分咨询专业人士', '给自己合理的考虑时间'], contextTags: ['合同', '决定', '犹豫']),
  EmotionKnowledgeEntry(id: 'anxiety_23', scenario: '担心存款不够用', emotionTags: ['不安全', '焦虑'], strategies: ['制定简单的收支计划', '建立应急基金', '咨询理财顾问'], contextTags: ['存款', '财务', '安全']),
  EmotionKnowledgeEntry(id: 'anxiety_24', scenario: '感觉身体不受控制', emotionTags: ['失控', '恐慌'], strategies: ['从深呼吸开始恢复控制感', '握紧拳头再慢慢松开', '提醒这是暂时的感觉'], contextTags: ['控制', '恐慌', '身体']),
  EmotionKnowledgeEntry(id: 'anxiety_25', scenario: '去新环境感到不适', emotionTags: ['陌生', '不安'], strategies: ['提前了解新环境的信息', '带一个让自己安心的物品', '给自己适应的时间'], contextTags: ['新环境', '陌生', '适应']),
  EmotionKnowledgeEntry(id: 'anxiety_26', scenario: '担心别人不喜欢自己', emotionTags: ['不安', '自卑'], strategies: ['不是所有人都需要喜欢你', '做真实的自己会吸引对的人', '把精力放在自我成长上'], contextTags: ['喜欢', '社交', '自卑']),
  EmotionKnowledgeEntry(id: 'anxiety_27', scenario: '做噩梦后心有余悸', emotionTags: ['恐惧', '不安'], strategies: ['醒来后开灯确认环境安全', '这是梦不是现实，你是安全的', '记下来和信任的人聊聊'], contextTags: ['噩梦', '恐惧', '睡眠']),
  EmotionKnowledgeEntry(id: 'anxiety_28', scenario: '觉得事情会往坏的方向发展', emotionTags: ['悲观', '焦虑'], strategies: ['问自己最坏的结果是什么', '写下事实证据而非想象', '大多数担心的事不会发生'], contextTags: ['悲观', '灾难化', '预测']),
  EmotionKnowledgeEntry(id: 'anxiety_29', scenario: '感觉心跳加速手心出汗', emotionTags: ['紧张', '身体反应'], strategies: ['这是正常的战斗逃跑反应', '用冷水洗手降温', '慢慢数到十平复情绪'], contextTags: ['心跳', '出汗', '紧张']),
  EmotionKnowledgeEntry(id: 'anxiety_30', scenario: '害怕改变不敢尝试新事物', emotionTags: ['恐惧', '犹豫'], strategies: ['从小的改变开始', '给自己设定一个尝试期限', '想象成功后的场景'], contextTags: ['改变', '尝试', '恐惧']),
  EmotionKnowledgeEntry(id: 'anxiety_31', scenario: '深夜想太多越想越怕', emotionTags: ['恐惧', '失眠'], strategies: ['设定一个担忧时间限时思考', '听白噪音或播客转移注意力', '明天再想今晚先休息'], contextTags: ['深夜', '失眠', '胡思乱想']),
  EmotionKnowledgeEntry(id: 'anxiety_32', scenario: '觉得事情太多无法承受', emotionTags: ['崩溃', '焦虑'], strategies: ['只做当前最重要的一件事', '向他人寻求帮助分担', '降低对自己的要求不是懒惰'], contextTags: ['太多', '崩溃', '压力']),
  EmotionKnowledgeEntry(id: 'anxiety_33', scenario: '被要求在众人面前发言', emotionTags: ['紧张', '恐惧'], strategies: ['充分准备并多次练习', '把注意力放在内容上', '观众希望你成功而非失败'], contextTags: ['演讲', '紧张', '公众']),
  EmotionKnowledgeEntry(id: 'anxiety_34', scenario: '感觉自己被监视或跟踪', emotionTags: ['恐惧', '不安全'], strategies: ['确认是否真实存在威胁', '和信任的人分享你的感受', '在安全的地方寻求帮助'], contextTags: ['监视', '恐惧', '安全']),
  EmotionKnowledgeEntry(id: 'anxiety_35', scenario: '对过去的错误耿耿于怀', emotionTags: ['内疚', '焦虑'], strategies: ['错误是成长的一部分', '写下从中学到了什么', '原谅过去的自己'], contextTags: ['错误', '内疚', '过去']),
];
