import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> suppressionEntries = [
  EmotionKnowledgeEntry(id: 'suppression_01', scenario: '工作压力大不敢表现出来', emotionTags: ['压抑', '隐忍'], strategies: ['找到信任的人倾诉', '下班后做释放压力的活动', '工作中的情绪需要出口'], contextTags: ['工作', '压力', '隐忍']),
  EmotionKnowledgeEntry(id: 'suppression_02', scenario: '被要求坚强不能哭', emotionTags: ['压抑', '委屈'], strategies: ['哭是正常的情绪表达', '找一个私密的空间释放', '坚强不意味着不能流泪'], contextTags: ['坚强', '哭', '压抑']),
  EmotionKnowledgeEntry(id: 'suppression_03', scenario: '觉得表达情绪是软弱', emotionTags: ['封闭', '自责'], strategies: ['表达情绪是勇敢的行为', '压抑反而会积累更大的爆发', '每个人都有脆弱的时候'], contextTags: ['软弱', '表达', '情绪']),
  EmotionKnowledgeEntry(id: 'suppression_04', scenario: '在父母面前报喜不报忧', emotionTags: ['隐忍', '孤独'], strategies: ['适当分享困难获得支持', '父母其实希望被你需要', '不必一个人扛所有'], contextTags: ['父母', '隐瞒', '报喜']),
  EmotionKnowledgeEntry(id: 'suppression_05', scenario: '职场中不能说真话', emotionTags: ['压抑', '无奈'], strategies: ['选择安全的表达方式', '找到职场外的倾诉渠道', '记录自己的真实想法'], contextTags: ['职场', '真话', '压抑']),
  EmotionKnowledgeEntry(id: 'suppression_06', scenario: '感情中总是忍让迁就', emotionTags: ['委屈', '不满'], strategies: ['健康的关系需要表达需求', '迁就不是长久之计', '学会说不不是自私'], contextTags: ['感情', '忍让', '迁就']),
  EmotionKnowledgeEntry(id: 'suppression_07', scenario: '怕给别人添麻烦不敢求助', emotionTags: ['孤立', '自立'], strategies: ['求助是正常的人际互动', '别人帮助你也会获得价值感', '不必什么都自己扛'], contextTags: ['求助', '麻烦', '自立']),
  EmotionKnowledgeEntry(id: 'suppression_08', scenario: '被教育男儿有泪不轻弹', emotionTags: ['压抑', '束缚'], strategies: ['性别不应该限制情绪表达', '男性同样需要情感出口', '压抑会影响身心健康'], contextTags: ['性别', '坚强', '表达']),
  EmotionKnowledgeEntry(id: 'suppression_09', scenario: '明明生气了却说没关系', emotionTags: ['压抑', '矛盾'], strategies: ['诚实地面对自己的感受', '用温和的方式表达不满', '没关系不代表真的没关系'], contextTags: ['生气', '没关系', '压抑']),
  EmotionKnowledgeEntry(id: 'suppression_10', scenario: '深夜独自消化情绪', emotionTags: ['孤独', '压抑'], strategies: ['写日记帮助整理情绪', '听音乐释放情绪', '白天找人聊聊'], contextTags: ['深夜', '独自', '消化']),
  EmotionKnowledgeEntry(id: 'suppression_11', scenario: '在权威面前不敢反驳', emotionTags: ['压抑', '恐惧'], strategies: ['你的意见同样有价值', '用数据和事实支撑观点', '选择合适的时机表达'], contextTags: ['权威', '反驳', '恐惧']),
  EmotionKnowledgeEntry(id: 'suppression_12', scenario: '难过时假装开心', emotionTags: ['伪装', '疲惫'], strategies: ['不必在所有人面前坚强', '和亲近的人做真实的自己', '假笑比真哭更累'], contextTags: ['假装', '开心', '伪装']),
  EmotionKnowledgeEntry(id: 'suppression_13', scenario: '总是为别人着想忽略自己', emotionTags: ['委屈', '疲惫'], strategies: ['你也是需要被照顾的人', '学会先满足自己的基本需求', '自私一点不是坏事'], contextTags: ['别人', '忽略', '自顾']),
  EmotionKnowledgeEntry(id: 'suppression_14', scenario: '被批评后强忍泪水', emotionTags: ['委屈', '压抑'], strategies: ['找一个没人的地方释放', '批评的内容可以反思，方式不必接受', '你的情绪反应是正常的'], contextTags: ['批评', '泪水', '委屈']),
  EmotionKnowledgeEntry(id: 'suppression_15', scenario: '在团队中不敢提反对意见', emotionTags: ['压抑', '焦虑'], strategies: ['好的团队需要不同的声音', '用建设性的方式提出异议', '沉默不等于认同'], contextTags: ['团队', '反对', '沉默']),
  EmotionKnowledgeEntry(id: 'suppression_16', scenario: '明明不想参加活动却答应了', emotionTags: ['违心', '疲惫'], strategies: ['学会真诚地说不', '别人的失望不是你的责任', '保护自己的时间和精力'], contextTags: ['答应', '违心', '拒绝']),
  EmotionKnowledgeEntry(id: 'suppression_17', scenario: '感觉不对但说不出来', emotionTags: ['困惑', '压抑'], strategies: ['尝试用文字描述感受', '找一个安静的时刻和自己对话', '情绪有时需要时间才能清晰'], contextTags: ['说不出来', '困惑', '感受']),
  EmotionKnowledgeEntry(id: 'suppression_18', scenario: '把所有责任都揽在自己身上', emotionTags: ['自责', '压力'], strategies: ['分清哪些是自己的责任', '团队的失败不是一个人的错', '学会分担和信任他人'], contextTags: ['责任', '自责', '揽']),
  EmotionKnowledgeEntry(id: 'suppression_19', scenario: '觉得求助很丢人', emotionTags: ['自尊', '压抑'], strategies: ['求助是智慧不是软弱', '每个人都需要帮助的时候', '帮助别人的人也希望被需要'], contextTags: ['求助', '丢人', '自尊']),
  EmotionKnowledgeEntry(id: 'suppression_20', scenario: '被误解后不解释', emotionTags: ['无奈', '冷漠'], strategies: ['选择值得解释的人去解释', '不解释不代表不委屈', '有些误解时间会证明'], contextTags: ['误解', '解释', '无奈']),
  EmotionKnowledgeEntry(id: 'suppression_21', scenario: '明明很想念却不联系', emotionTags: ['思念', '克制'], strategies: ['思念是美好的情感', '一条简单的消息不会打扰', '勇敢表达你的想念'], contextTags: ['想念', '联系', '克制']),
  EmotionKnowledgeEntry(id: 'suppression_22', scenario: '受到伤害选择沉默', emotionTags: ['受伤', '压抑'], strategies: ['沉默不是永远的选择', '找到安全的人倾诉', '你有权利为自己发声'], contextTags: ['伤害', '沉默', '受伤']),
  EmotionKnowledgeEntry(id: 'suppression_23', scenario: '害怕冲突避免表达不满', emotionTags: ['回避', '焦虑'], strategies: ['冲突不一定是坏事', '用我语句表达感受', '回避问题不会让它消失'], contextTags: ['冲突', '回避', '不满']),
  EmotionKnowledgeEntry(id: 'suppression_24', scenario: '在家庭中扮演懂事的角色', emotionTags: ['压抑', '疲惫'], strategies: ['你不必永远懂事', '家庭也需要真实的情感交流', '适当示弱是亲密的表现'], contextTags: ['家庭', '懂事', '角色']),
  EmotionKnowledgeEntry(id: 'suppression_25', scenario: '工作失败了不愿告诉家人', emotionTags: ['隐瞒', '压力'], strategies: ['家人的支持比想象中重要', '失败不是耻辱', '你的价值不由工作定义'], contextTags: ['工作', '失败', '隐瞒']),
  EmotionKnowledgeEntry(id: 'suppression_26', scenario: '把情绪藏在笑容后面', emotionTags: ['伪装', '疲惫'], strategies: ['允许自己不总是笑着', '你的感受值得被认真对待', '找到一个可以卸下伪装的地方'], contextTags: ['笑容', '伪装', '情绪']),
  EmotionKnowledgeEntry(id: 'suppression_27', scenario: '被冒犯了还说没关系', emotionTags: ['委屈', '压抑'], strategies: ['你的感受是正当的', '有必要让对方知道边界', '你不必为了和气委屈自己'], contextTags: ['冒犯', '没关系', '委屈']),
  EmotionKnowledgeEntry(id: 'suppression_28', scenario: '总是把自己的需求放在最后', emotionTags: ['忽略', '自损'], strategies: ['你不是不重要', '先照顾好自己才能照顾别人', '每天给自己留10分钟'], contextTags: ['需求', '最后', '自顾']),
  EmotionKnowledgeEntry(id: 'suppression_29', scenario: '感到痛苦却说还好', emotionTags: ['压抑', '逞强'], strategies: ['诚实面对自己的状态', '还好不等于真的好', '寻求帮助是勇敢的选择'], contextTags: ['还好', '逞强', '痛苦']),
  EmotionKnowledgeEntry(id: 'suppression_30', scenario: '被不公平对待选择忍耐', emotionTags: ['压抑', '无奈'], strategies: ['忍耐不是唯一的选项', '记录事实寻求正当途径解决', '维护自己的权益不是找事'], contextTags: ['不公平', '忍耐', '维权']),
  EmotionKnowledgeEntry(id: 'suppression_31', scenario: '在社交媒体上只展示好的一面', emotionTags: ['表演', '空虚'], strategies: ['社交媒体不等于真实生活', '允许自己有不完美的时候', '找到真实表达的安全空间'], contextTags: ['社交媒体', '表演', '完美']),
  EmotionKnowledgeEntry(id: 'suppression_32', scenario: '觉得表达需求是给别人添麻烦', emotionTags: ['自责', '压抑'], strategies: ['表达需求是健康的行为', '你不说别人怎么知道', '合理的需求不是麻烦'], contextTags: ['需求', '麻烦', '自责']),
  EmotionKnowledgeEntry(id: 'suppression_33', scenario: '明明想拒绝却总是答应', emotionTags: ['违心', '疲惫'], strategies: ['练习说不从小事开始', '你的拒绝不会毁掉关系', '设限是自我保护'], contextTags: ['拒绝', '答应', '违心']),
  EmotionKnowledgeEntry(id: 'suppression_34', scenario: '害怕被评价而隐藏真实想法', emotionTags: ['恐惧', '压抑'], strategies: ['真实比完美更受欢迎', '你的想法值得被听到', '找安全的人先练习表达'], contextTags: ['评价', '真实', '隐藏']),
  EmotionKnowledgeEntry(id: 'suppression_35', scenario: '一直假装没事直到崩溃', emotionTags: ['压抑', '崩溃'], strategies: ['崩溃是长期压抑的结果', '学会在崩溃前释放', '定期给自己做情绪检查'], contextTags: ['崩溃', '假装', '压抑']),
];
