import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> angerEntries = [
  EmotionKnowledgeEntry(id: 'anger_01', scenario: '被不公平对待', emotionTags: ['愤怒', '委屈'], strategies: ['先离开现场冷静', '写下来理清自己的感受', '用我开头的句式表达不满而非指责'], contextTags: ['不公平', '对待', '委屈']),
  EmotionKnowledgeEntry(id: 'anger_02', scenario: '被欺骗或背叛', emotionTags: ['愤怒', '受伤'], strategies: ['给自己时间冷静再沟通', '评估这段关系是否值得维护', '和信任的人倾诉释放情绪'], contextTags: ['欺骗', '背叛', '信任']),
  EmotionKnowledgeEntry(id: 'anger_03', scenario: '被人插队或抢座', emotionTags: ['气愤', '不满'], strategies: ['深呼吸数到十', '想一想对方可能有急事', '不必为小事影响自己的心情'], contextTags: ['插队', '公共', '小事']),
  EmotionKnowledgeEntry(id: 'anger_04', scenario: '工作被抢功劳', emotionTags: ['愤怒', '不公'], strategies: ['记录自己的工作成果', '选择合适的时机向上级反映', '在团队中建立自己的专业声望'], contextTags: ['工作', '功劳', '不公']),
  EmotionKnowledgeEntry(id: 'anger_05', scenario: '家人说伤害性的话', emotionTags: ['愤怒', '心痛'], strategies: ['暂时离开冷静', '待情绪平复后沟通你的感受', '区分对方的意图和效果'], contextTags: ['家人', '言语', '伤害']),
  EmotionKnowledgeEntry(id: 'anger_06', scenario: '被骗钱或上当', emotionTags: ['愤怒', '自责'], strategies: ['及时报警或寻求法律帮助', '不要过度自责，骗子很狡猾', '总结经验防止再次被骗'], contextTags: ['被骗', '金钱', '自责']),
  EmotionKnowledgeEntry(id: 'anger_07', scenario: '交通堵车无法移动', emotionTags: ['焦躁', '愤怒'], strategies: ['听喜欢的播客或音乐', '利用时间做简单思考', '接受堵车是不可控的'], contextTags: ['交通', '堵车', '等待']),
  EmotionKnowledgeEntry(id: 'anger_08', scenario: '被别人嘲笑或贬低', emotionTags: ['愤怒', '受伤'], strategies: ['对方的话不代表你的价值', '远离不尊重你的人', '用成就回应质疑'], contextTags: ['嘲笑', '贬低', '自尊']),
  EmotionKnowledgeEntry(id: 'anger_09', scenario: '伴侣不理解自己', emotionTags: ['失望', '烦躁'], strategies: ['选择平静的时机沟通', '用我感觉的句式而非你总是', '尝试理解对方的视角'], contextTags: ['伴侣', '理解', '沟通']),
  EmotionKnowledgeEntry(id: 'anger_10', scenario: '自己的东西被人乱动', emotionTags: ['不满', '烦躁'], strategies: ['表达自己的边界和需求', '不必为小事大动肝火', '给自己的物品标注归属'], contextTags: ['物品', '边界', '尊重']),
  EmotionKnowledgeEntry(id: 'anger_11', scenario: '被冤枉做了没做的事', emotionTags: ['愤怒', '委屈'], strategies: ['冷静收集证据为自己辩护', '找第三方帮忙澄清', '不要急于爆发，事实会说话'], contextTags: ['冤枉', '辩解', '委屈']),
  EmotionKnowledgeEntry(id: 'anger_12', scenario: '孩子不听话反复犯错', emotionTags: ['烦躁', '无力'], strategies: ['先处理自己的情绪再教育', '理解行为背后的需求', '设定清晰的一致性规则'], contextTags: ['孩子', '教育', '烦躁']),
  EmotionKnowledgeEntry(id: 'anger_13', scenario: '承诺的事情对方没有做到', emotionTags: ['失望', '愤怒'], strategies: ['直接表达你的失望', '了解对方没做到的原因', '重新评估对这个人的信任度'], contextTags: ['承诺', '信任', '失望']),
  EmotionKnowledgeEntry(id: 'anger_14', scenario: '网络上看到不公正的事', emotionTags: ['愤怒', '义愤'], strategies: ['理性表达而非网络暴力', '关注自己能做出的积极改变', '限制浏览时间避免情绪耗竭'], contextTags: ['网络', '不公', '愤怒']),
  EmotionKnowledgeEntry(id: 'anger_15', scenario: '自己犯了低级错误', emotionTags: ['懊恼', '愤怒'], strategies: ['原谅自己的不完美', '分析错误原因下次避免', '不要反复自我批评'], contextTags: ['错误', '懊恼', '自责']),
  EmotionKnowledgeEntry(id: 'anger_16', scenario: '被临时取消计划', emotionTags: ['不满', '失望'], strategies: ['表达自己的失望', '对方可能有不得已的原因', '利用空出来的时间做喜欢的事'], contextTags: ['取消', '计划', '失望']),
  EmotionKnowledgeEntry(id: 'anger_17', scenario: '团队合作中有人偷懒', emotionTags: ['不满', '不公平'], strategies: ['私下和对方沟通', '必要时向领导反映', '做好自己的部分'], contextTags: ['团队', '偷懒', '合作']),
  EmotionKnowledgeEntry(id: 'anger_18', scenario: '一直忍让终于爆发', emotionTags: ['愤怒', '委屈'], strategies: ['学会及时表达不满', '设定健康的人际边界', '愤怒本身不是错，如何表达才重要'], contextTags: ['忍让', '爆发', '边界']),
  EmotionKnowledgeEntry(id: 'anger_19', scenario: '遭遇歧视或偏见', emotionTags: ['愤怒', '受伤'], strategies: ['这不是你的问题', '找到支持你的群体', '用行动证明偏见是错的'], contextTags: ['歧视', '偏见', '公平']),
  EmotionKnowledgeEntry(id: 'anger_20', scenario: '信任的人泄露了秘密', emotionTags: ['愤怒', '背叛'], strategies: ['选择对的人倾诉，重新评估信任', '和对方严肃谈话', '允许自己不原谅'], contextTags: ['秘密', '背叛', '信任']),
  EmotionKnowledgeEntry(id: 'anger_21', scenario: '排队很久前面的人办很久', emotionTags: ['焦躁', '不满'], strategies: ['利用等待时间做其他事', '理解工作人员也有难处', '如果很急可以改天再来'], contextTags: ['排队', '等待', '焦躁']),
  EmotionKnowledgeEntry(id: 'anger_22', scenario: '被要求做分外的事', emotionTags: ['不满', '委屈'], strategies: ['学会合理拒绝', '表达自己目前的工作量', '必要时和上级沟通职责范围'], contextTags: ['拒绝', '分外', '边界']),
  EmotionKnowledgeEntry(id: 'anger_23', scenario: '觉得自己被当枪使', emotionTags: ['愤怒', '背叛'], strategies: ['冷静分析事实', '和相关人直接沟通', '以后做事留证据'], contextTags: ['利用', '背叛', '愤怒']),
  EmotionKnowledgeEntry(id: 'anger_24', scenario: '多次建议对方不听', emotionTags: ['无力', '烦躁'], strategies: ['接受每个人有自己的选择', '只在被请求时给建议', '管理好自己的期待'], contextTags: ['建议', '不听', '无力']),
  EmotionKnowledgeEntry(id: 'anger_25', scenario: '噪音打扰无法休息', emotionTags: ['烦躁', '愤怒'], strategies: ['和邻居友好沟通', '使用耳塞或白噪音', '必要时寻求物业协助'], contextTags: ['噪音', '休息', '打扰']),
  EmotionKnowledgeEntry(id: 'anger_26', scenario: '购物遇到态度差的店员', emotionTags: ['不快', '愤怒'], strategies: ['不必和对方争执', '换一家店或找其他店员', '不要让别人的态度影响自己'], contextTags: ['服务', '态度', '购物']),
  EmotionKnowledgeEntry(id: 'anger_27', scenario: '被背后说坏话', emotionTags: ['愤怒', '受伤'], strategies: ['真正在乎你的人不会相信谣言', '直接和对方当面沟通', '做好自己让事实说话'], contextTags: ['背后', '坏话', '谣言']),
  EmotionKnowledgeEntry(id: 'anger_28', scenario: '努力了很久没得到想要的结果', emotionTags: ['挫败', '愤怒'], strategies: ['承认挫败感是正常的', '重新评估方法是否需要调整', '休息一下再重新出发'], contextTags: ['努力', '结果', '挫败']),
  EmotionKnowledgeEntry(id: 'anger_29', scenario: '被人当面质疑能力', emotionTags: ['愤怒', '自尊'], strategies: ['用事实和成果回应', '不必急于证明自己', '记住你的价值不由别人定义'], contextTags: ['质疑', '能力', '自尊']),
  EmotionKnowledgeEntry(id: 'anger_30', scenario: '社会事件引发强烈愤怒', emotionTags: ['愤怒', '无力'], strategies: ['允许自己感受愤怒', '转化为建设性的行动', '和志同道合的人一起发声'], contextTags: ['社会', '事件', '正义']),
  EmotionKnowledgeEntry(id: 'anger_31', scenario: '被强迫做不愿意的事', emotionTags: ['愤怒', '抗拒'], strategies: ['坚定表达自己的立场', '寻求他人的支持', '你有权说不'], contextTags: ['强迫', '不愿', '自主']),
  EmotionKnowledgeEntry(id: 'anger_32', scenario: '信任的系统或机构出问题', emotionTags: ['失望', '愤怒'], strategies: ['理性反馈问题', '寻找替代方案', '不把对系统的不满发泄到个人身上'], contextTags: ['系统', '机构', '失望']),
  EmotionKnowledgeEntry(id: 'anger_33', scenario: '运动或比赛输了不服气', emotionTags: ['不甘', '愤怒'], strategies: ['把不服气转化为训练动力', '分析对手的优势学习', '输赢是竞技的一部分'], contextTags: ['比赛', '输', '不服']),
  EmotionKnowledgeEntry(id: 'anger_34', scenario: '自己的好意被误解', emotionTags: ['委屈', '心寒'], strategies: ['不要急于辩解，让时间说明', '下次注意表达方式', '不是所有人都能理解你的好意'], contextTags: ['好意', '误解', '委屈']),
  EmotionKnowledgeEntry(id: 'anger_35', scenario: '感觉被生活欺负', emotionTags: ['愤怒', '无力'], strategies: ['写下具体让你愤怒的事', '能改变的去改变，不能改变的接受', '你不是一个人在战斗'], contextTags: ['生活', '无力', '困境']),
];
