import 'emotion_knowledge_entry.dart';

final List<EmotionKnowledgeEntry> calmnessEntries = [
  EmotionKnowledgeEntry(id: 'calmness_01', scenario: '难以静下心来', emotionTags: ['烦躁', '焦躁'], strategies: ['找个安静角落闭眼做几次深呼吸', '听舒缓白噪音或轻音乐', '把焦虑的事情写下来释放'], contextTags: ['静心', '烦躁', '专注']),
  EmotionKnowledgeEntry(id: 'calmness_02', scenario: '事情太多感到紧绷', emotionTags: ['紧绷', '忙碌'], strategies: ['列出待办并按优先级排序', '只专注眼前的一件事', '给自己安排固定的休息时间'], contextTags: ['忙碌', '紧绷', '待办']),
  EmotionKnowledgeEntry(id: 'calmness_03', scenario: '睡前思绪纷乱', emotionTags: ['失眠', '烦躁'], strategies: ['做4-7-8呼吸练习', '听助眠音频放空', '把脑海里的想法写下来清空'], contextTags: ['睡前', '失眠', '思绪']),
  EmotionKnowledgeEntry(id: 'calmness_04', scenario: '想找回内心宁静', emotionTags: ['渴望平静', '疲惫'], strategies: ['每天留10分钟独处静坐', '到大自然中散散步', '练习正念关注呼吸'], contextTags: ['宁静', '独处', '正念']),
  EmotionKnowledgeEntry(id: 'calmness_05', scenario: '享受安静的独处', emotionTags: ['平静', '放松'], strategies: ['泡一杯热茶慢慢品', '读一本喜欢的书', '写日记记录此刻感受'], contextTags: ['独处', '安静', '放松']),
  EmotionKnowledgeEntry(id: 'calmness_06', scenario: '感到生活安稳知足', emotionTags: ['知足', '平静'], strategies: ['感恩当下拥有的一切', '与亲友分享这份安好', '保持这份从容的节奏'], contextTags: ['知足', '安稳', '感恩']),
  EmotionKnowledgeEntry(id: 'calmness_07', scenario: '想培养正念习惯', emotionTags: ['专注', '平和'], strategies: ['每天固定时间冥想5分钟', '吃饭时专心感受食物', '走路时关注脚步和呼吸'], contextTags: ['正念', '冥想', '习惯']),
  EmotionKnowledgeEntry(id: 'calmness_08', scenario: '运动后身心舒畅', emotionTags: ['舒畅', '放松'], strategies: ['做温和的拉伸放松肌肉', '喝温水补充水分', '享受运动后的平静时刻'], contextTags: ['运动', '舒畅', '放松']),
  EmotionKnowledgeEntry(id: 'calmness_09', scenario: '想保持情绪平稳', emotionTags: ['稳定', '平和'], strategies: ['保持规律的作息', '减少摄入过量咖啡因', '定期运动释放压力'], contextTags: ['平稳', '规律', '运动']),
  EmotionKnowledgeEntry(id: 'calmness_10', scenario: '感到被大自然治愈', emotionTags: ['治愈', '宁静'], strategies: ['多到公园或绿地走走', '观察花草树木的细节', '感受阳光和微风'], contextTags: ['自然', '治愈', '户外']),
  EmotionKnowledgeEntry(id: 'calmness_11', scenario: '想体验慢生活', emotionTags: ['放松', '从容'], strategies: ['减少不必要的安排', '放慢脚步观察周围', '享受一顿不赶时间的饭'], contextTags: ['慢生活', '从容', '节奏']),
  EmotionKnowledgeEntry(id: 'calmness_12', scenario: '想要睡个好觉', emotionTags: ['疲惫', '放松'], strategies: ['睡前1小时远离屏幕', '保持卧室安静昏暗', '洗个温水澡放松身心'], contextTags: ['睡眠', '休息', '睡前']),
  EmotionKnowledgeEntry(id: 'calmness_13', scenario: '学会放下焦虑', emotionTags: ['释怀', '轻松'], strategies: ['区分可控与不可控的事', '把注意力拉回当下', '告诉自己已经尽力了'], contextTags: ['放下', '释怀', '焦虑']),
  EmotionKnowledgeEntry(id: 'calmness_14', scenario: '想给自己温柔时刻', emotionTags: ['自我关怀', '温暖'], strategies: ['做一件让自己开心的小事', '允许自己休息而不内疚', '对自己说一句鼓励的话'], contextTags: ['温柔', '自我关怀', '休息']),
  EmotionKnowledgeEntry(id: 'calmness_15', scenario: '感到内心清明', emotionTags: ['清明', '平静'], strategies: ['保持这份清晰的状态', '记录此刻的想法', '为明天做个简单计划'], contextTags: ['清明', '清晰', '规划']),
  EmotionKnowledgeEntry(id: 'calmness_16', scenario: '想减少情绪波动', emotionTags: ['平稳', '安定'], strategies: ['观察情绪而不被它带走', '情绪来临时先深呼吸', '找到稳定的情绪锚点'], contextTags: ['波动', '安定', '情绪']),
  EmotionKnowledgeEntry(id: 'calmness_17', scenario: '享受一杯茶或咖啡', emotionTags: ['惬意', '放松'], strategies: ['专注感受香气和温度', '放空思绪慢慢品', '享受这段不被打扰的时光'], contextTags: ['茶', '咖啡', '惬意']),
  EmotionKnowledgeEntry(id: 'calmness_18', scenario: '想要真正放松下来', emotionTags: ['紧绷', '疲惫'], strategies: ['做渐进式肌肉放松', '泡个热水澡', '暂时放下所有待办'], contextTags: ['放松', '紧绷', '休息']),
  EmotionKnowledgeEntry(id: 'calmness_19', scenario: '感到生活节奏很好', emotionTags: ['从容', '满足'], strategies: ['继续保持当前的节奏', '记录下让你舒服的安排', '与重要的人分享这份满足'], contextTags: ['节奏', '满足', '从容']),
  EmotionKnowledgeEntry(id: 'calmness_20', scenario: '想练习深呼吸', emotionTags: ['放松', '平静'], strategies: ['吸气4秒屏息7秒呼气8秒', '把手放在腹部感受起伏', '每天睡前练习几分钟'], contextTags: ['深呼吸', '呼吸', '练习']),
  EmotionKnowledgeEntry(id: 'calmness_21', scenario: '想要拥抱当下', emotionTags: ['珍惜', '平静'], strategies: ['感受此刻身边的美好', '减少对过去的纠结', '不过分担忧未来'], contextTags: ['当下', '珍惜', '此刻']),
  EmotionKnowledgeEntry(id: 'calmness_22', scenario: '感到被音乐治愈', emotionTags: ['治愈', '平和'], strategies: ['听一首舒缓的纯音乐', '闭上眼睛沉浸旋律', '用音乐配合深呼吸'], contextTags: ['音乐', '治愈', '旋律']),
  EmotionKnowledgeEntry(id: 'calmness_23', scenario: '想告别忙碌找回自己', emotionTags: ['疲惫', '迷失'], strategies: ['每天留出完全属于自己的时间', '做一件喜欢但被搁置的事', '学会对不必要的事说不'], contextTags: ['忙碌', '找回自己', '边界']),
  EmotionKnowledgeEntry(id: 'calmness_24', scenario: '感到内心柔软安宁', emotionTags: ['安宁', '温柔'], strategies: ['珍惜这份难得的平静', '做点温柔的事善待自己', '把这份感受记下来'], contextTags: ['安宁', '柔软', '平静']),
  EmotionKnowledgeEntry(id: 'calmness_25', scenario: '想建立平静的早晨', emotionTags: ['从容', '有序'], strategies: ['早起10分钟不慌不忙', '喝杯温水开启一天', '做个简单的晨间拉伸'], contextTags: ['早晨', '从容', '习惯']),
  EmotionKnowledgeEntry(id: 'calmness_26', scenario: '享受一个人的时光', emotionTags: ['自在', '平静'], strategies: ['做一顿想吃的饭', '看一部想看的电影', '享受不被打扰的自由'], contextTags: ['独处', '自在', '自由']),
  EmotionKnowledgeEntry(id: 'calmness_27', scenario: '想放下对完美的执念', emotionTags: ['释怀', '轻松'], strategies: ['接纳不完美的自己', '把应该换成可以', '庆祝每一个小进步'], contextTags: ['完美', '释怀', '接纳']),
  EmotionKnowledgeEntry(id: 'calmness_28', scenario: '感到心态平和从容', emotionTags: ['平和', '稳定'], strategies: ['保持这份从容的状态', '遇事先停顿再反应', '用长远眼光看待问题'], contextTags: ['平和', '从容', '稳定']),
  EmotionKnowledgeEntry(id: 'calmness_29', scenario: '想保持好心情', emotionTags: ['愉悦', '平静'], strategies: ['记录每天的小确幸', '与乐观的人多相处', '保持运动和充足睡眠'], contextTags: ['好心情', '愉悦', '运动']),
  EmotionKnowledgeEntry(id: 'calmness_30', scenario: '感到身心需要休息', emotionTags: ['疲惫', '休整'], strategies: ['给自己安排完整的休息日', '早点睡觉恢复精力', '做点低强度的放松活动'], contextTags: ['休息', '疲惫', '恢复']),
  EmotionKnowledgeEntry(id: 'calmness_31', scenario: '想与自然建立连接', emotionTags: ['宁静', '治愈'], strategies: ['常开窗呼吸新鲜空气', '养一盆绿植照顾它', '周末到户外走一走'], contextTags: ['自然', '绿植', '户外']),
  EmotionKnowledgeEntry(id: 'calmness_32', scenario: '学会活在当下', emotionTags: ['专注', '平静'], strategies: ['一次只做一件事', '觉察呼吸把自己带回当下', '减少同时处理多件事'], contextTags: ['当下', '专注', '觉察']),
  EmotionKnowledgeEntry(id: 'calmness_33', scenario: '感到内心强大而平静', emotionTags: ['笃定', '平静'], strategies: ['记住这份笃定的力量', '需要时回到这个状态', '用它面对生活的挑战'], contextTags: ['笃定', '强大', '平静']),
  EmotionKnowledgeEntry(id: 'calmness_34', scenario: '想要夜间安眠', emotionTags: ['放松', '安眠'], strategies: ['建立固定的睡前仪式', '睡前做温和拉伸', '保持卧室温度适宜'], contextTags: ['安眠', '睡前', '仪式']),
  EmotionKnowledgeEntry(id: 'calmness_35', scenario: '享受生活的美好瞬间', emotionTags: ['感恩', '愉悦'], strategies: ['用心感受和记录美好', '与爱的人分享快乐', '常怀感恩之心'], contextTags: ['美好', '感恩', '分享']),
];
